FROM centos:6

# Install Ansible
RUN yum -y update; yum clean all;
RUN yum -y install epel-release
RUN yum -y install git sudo ansible
RUN yum clean all

# Install cloudwatch scripts dependencies
RUN yum -y install initscripts
RUN yum -y install cronie
RUN yum -y install which
RUN yum -y install python-pip 

# Disable requiretty
RUN sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/'  /etc/sudoers

# Install Ansible inventory file
RUN echo -e '[local]\nlocalhost ansible_connection=local' > /etc/ansible/hosts

CMD ["/usr/sbin/init"]
